// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button'];
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox'];
    AForm: typeof import('@arco-design/web-vue')['Form'];
    AFormItem: typeof import('@arco-design/web-vue')['FormItem'];
    AInput: typeof import('@arco-design/web-vue')['Input'];
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword'];
    AMenu: typeof import('@arco-design/web-vue')['Menu'];
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem'];
    APopover: typeof import('@arco-design/web-vue')['Popover'];
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu'];
    ATable: typeof import('@arco-design/web-vue')['Table'];
    ATableColumn: typeof import('@arco-design/web-vue')['TableColumn'];
    Layouts: typeof import('./src/components/layouts/Layouts.vue')['default'];
    LeftMenus: typeof import('./src/components/layouts/components/leftMenus/index.vue')['default'];
    NavMenus: typeof import('./src/components/layouts/components/navMenus/index.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
